function [Vux,Vuz]=Linv_fdt(fdt,Linv,Msin,Mp1,Mp3,settings,zero_row,k)
    
    fdt=Msin*fdt;fdt(k,:)=zero_row;
    temp=sum(bsxfun(@times,Linv,...
        reshape(fdt,1,settings.n*settings.m,settings.N_mesh)),2);
    f_dt=reshape(temp(1:settings.n*settings.m,1,:),...
        settings.n*settings.m,settings.N_mesh);

    Vux=real(settings.Mint*(Mp1*...
        reshape(f_dt,settings.n*settings.m,settings.N_mesh)))*(2*pi);
    Vuz=real(settings.Mint*(Mp3*...
        reshape(f_dt,settings.n*settings.m,settings.N_mesh)))*(2*pi);
end